"""
Evaluate tweet→need extraction against the hand-labelled sample.

Compares the deterministic rule-based extractor with the local-LLM extractor
(llama3.2:1b, strict JSON contract) on data/disaster_tweets_sample.csv and
writes the results table to docs/extraction_eval.md.

Usage:
    python scripts/evaluate_extraction.py            # rule-based only (offline)
    python scripts/evaluate_extraction.py --llm      # also evaluate the LLM extractor
    python scripts/evaluate_extraction.py --show-misses
"""

import argparse
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from resq_project.coordination import extract_need_from_text
from resq_project.tweet_triage import (
    evaluate_extraction,
    extract_need_hybrid,
    extract_need_with_llm,
    load_tweet_feed,
)

FIELDS = ["category", "urgency", "quantity", "location"]
DOCS_OUT = Path(__file__).resolve().parents[1] / "docs" / "extraction_eval.md"


def print_report(name: str, result: dict, show_misses: bool) -> None:
    acc = result["accuracy"]
    print(f"\n{name}  (n={result['n']} labelled tweets)")
    print("  " + " · ".join(f"{f}: {acc[f]:.1%}" for f in FIELDS))
    print(f"  overall field accuracy: {result['overall']:.1%}")
    if show_misses:
        for row in result["rows"]:
            misses = [f"{f} {row[f]}" for f in FIELDS if row[f] != "✓"]
            if misses:
                print(f"  {row['tweet_id']}: {' | '.join(misses)}")


def markdown_section(name: str, result: dict) -> str:
    acc = result["accuracy"]
    lines = [f"### {name}", "",
             "| Field | Accuracy |", "|---|---|"]
    lines += [f"| {f} | {acc[f]:.1%} |" for f in FIELDS]
    lines += [f"| **overall** | **{result['overall']:.1%}** |", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--llm", action="store_true",
                    help="also evaluate the LLM extractor (needs Ollama running)")
    ap.add_argument("--show-misses", action="store_true",
                    help="print per-tweet mismatches")
    args = ap.parse_args()

    tweets = load_tweet_feed()
    if not tweets:
        sys.exit("No labelled tweets found — expected data/disaster_tweets_sample.csv")

    sections = []

    rule = evaluate_extraction(extract_need_from_text, tweets)
    print_report("Rule-based extractor (keyword heuristics)", rule, args.show_misses)
    sections.append(markdown_section("Rule-based extractor (keyword heuristics)", rule))

    if args.llm:
        from resq_project.workflow import get_llm

        probe = extract_need_with_llm(tweets[0]["text"], get_llm)
        if "fallback" in probe.get("extraction", ""):
            print("\n⚠ LLM unreachable (fell back to rules) — is Ollama running? Skipping LLM eval.")
        else:
            llm_result = evaluate_extraction(
                lambda text: extract_need_with_llm(text, get_llm), tweets)
            print_report("LLM extractor (llama3.2:1b, JSON contract)", llm_result, args.show_misses)
            sections.append(markdown_section("LLM extractor (llama3.2:1b, JSON contract)", llm_result))

            hybrid_result = evaluate_extraction(
                lambda text: extract_need_hybrid(text, get_llm), tweets)
            print_report("Hybrid extractor (LLM category/location + rule urgency/quantity)",
                         hybrid_result, args.show_misses)
            sections.append(markdown_section(
                "Hybrid extractor (LLM category/location + rule urgency/quantity)", hybrid_result))

    DOCS_OUT.write_text(
        f"# Tweet→Need Extraction Evaluation\n\n"
        f"Evaluated on `data/disaster_tweets_sample.csv` — a hand-labelled starter sample "
        f"styled on the Kaggle Disaster Tweets format ({rule['n']} tweets, synthetic starter "
        f"data as permitted by the project brief). Fields: category, urgency, quantity, "
        f"location. Generated by `scripts/evaluate_extraction.py` on {date.today().isoformat()}.\n\n"
        + "\n".join(sections)
        + "\nRe-run with `--llm` (Ollama required) to refresh the LLM comparison; "
          "`--show-misses` prints each mismatch for error analysis.\n"
    )
    print(f"\nWrote {DOCS_OUT}")


if __name__ == "__main__":
    main()
